### ISSUE TITLE
[CRITICAL-285] Skipped. Expected quality not found!

### ISSUE THREAD

**Issue by falcon1230** [nishad/udemy-dl#233] opened 2017-07-08 06:09 UTC
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [ ] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [ ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ ] I have checked that the issue I'm posting isn't already reported.
- [ ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

{issue content here, replace this line with your issue content}

**Comment by falcon1230** [comment] 2017-07-08 06:10
Hello, 
Can you please help me out with this issue.

Thanks.

**Comment by AgentSam** [comment] 2017-07-08 11:46
Latest alpha version (0.2.2a2) is working fine here.

To remove the old version and install the latest alpha, you might need to do the following:

```
sudo pip uninstall udemy-dl
sudo pip install udemy-dl==0.2.2a2

```

**Comment by falcon1230** [comment] 2017-07-08 11:56
Hey I did this but it is still replicating,
Has it got anything to do with python version?
I am currently on python 2.7.10, but I have both the versions of python installed.

Thanks

**Comment by AgentSam** [comment] 2017-07-08 12:28
Hey. I guess it might make some difference. It looks like my PIP default to python 3.4 at the moment. And like I said, upgrades/works without a hitch using the above commands.

There's also a page about installing the latest development version, here:
[install latest development version](https://github.com/nishad/udemy-dl/wiki/Installing-development-version)

But I would imagine that does the same as my previous commands.

Good luck...

**Comment by n3x77** [comment] 2017-07-08 12:44
Hey guys, 

I can confirm it works with the current master. 

I created a new virtual env for udemy-dl and installed udemy-dl with pip in that environment using the following command.
```bash
# create the virtual env
virtualenv /tmp/myEnv
#activate the env
source /tmp/myEnv/bin/activate
#install from git
pip install -U git+https://github.com/nishad/udemy-dl.git@master --ignore-installed six
```
After that im able to download courses with udemy-dl without the quality error. 
I figured out that if I am using the -q argument the download does not work and the quality error occurs, so just start the download without the -q argument.

Cheers
Sven

**Comment by falcon1230** [comment] 2017-07-08 14:00
Hey guys,
It worked when I switched my python environment to python 3.
Thanks.

**Comment by pra7792dip** [comment] 2017-07-08 23:28
Hi guys,

I had also same issue in python 2.7.10 with ubuntu 16.04

This is what I did to solve the issue.

I completely uninstalled the previous package by 
sudo pip uninstall udemy-dl

and clone the original repository by
git clone https://github.com/nishad/udemy-dl.git

then,

cd udemy-dl/src
./udemy-dl https://course-url

This worked for me.

**Comment by nishad** [comment] 2017-07-09 09:57
Duplicate of https://github.com/nishad/udemy-dl/issues/231.

**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.

**Closed by nishad** 2017-07-09 09:57 UTC
Labels: duplicate
