### ISSUE TITLE
[ERROR-61] Exception

### ISSUE THREAD

**Issue by madmax2** [nishad/udemy-dl#211] opened 2017-04-19 03:51 UTC
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [x] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---
After finishing the download of a course
I get this error message..

[ERROR-61] Exception
Traceback (most recent call last):
  File "C:\Python\Python352-32\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Python\Python352-32\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Python\Python352-32\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python\Python352-32\lib\http\client.py", line 1197, in getresponse
    response.begin()
  File "C:\Python\Python352-32\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Python\Python352-32\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Python\Python352-32\lib\socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "C:\Python\Python352-32\lib\ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Python\Python352-32\lib\ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "C:\Python\Python352-32\lib\ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\Python352-32\lib\site-packages\requests\adapters.py", line 423, in send
    timeout=timeout
  File "C:\Python\Python352-32\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 649, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Python\Python352-32\lib\site-packages\requests\packages\urllib3\util\retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Python\Python352-32\lib\site-packages\requests\packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Python\Python352-32\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "C:\Python\Python352-32\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 386, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Python\Python352-32\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 382, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Python\Python352-32\lib\http\client.py", line 1197, in getresponse
    response.begin()
  File "C:\Python\Python352-32\lib\http\client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "C:\Python\Python352-32\lib\http\client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Python\Python352-32\lib\socket.py", line 575, in readinto
    return self._sock.recv_into(b)
  File "C:\Python\Python352-32\lib\ssl.py", line 929, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Python\Python352-32\lib\ssl.py", line 791, in read
    return self._sslobj.read(len, buffer)
  File "C:\Python\Python352-32\lib\ssl.py", line 575, in read
    v = self._sslobj.read(len, buffer)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python\Python352-32\Scripts\udemy-dl", line 7, in <module>
    main()
  File "C:\Python\Python352-32\lib\site-packages\udemy_dl\udemy_dl.py", line 947, in main
    save_links, safe_file_names, just_list, output_dest, dir_use_course_title)
  File "C:\Python\Python352-32\lib\site-packages\udemy_dl\udemy_dl.py", line 809, in udemy_dl
    session.get(LOGOUT_URL)
  File "C:\Python\Python352-32\lib\site-packages\udemy_dl\udemy_dl.py", line 91, in get
    return self.session.get(url, headers=self.headers)
  File "C:\Python\Python352-32\lib\site-packages\requests\sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python\Python352-32\lib\site-packages\requests\sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python\Python352-32\lib\site-packages\requests\sessions.py", line 630, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Python\Python352-32\lib\site-packages\requests\sessions.py", line 630, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Python\Python352-32\lib\site-packages\requests\sessions.py", line 190, in resolve_redirects
    **adapter_kwargs
  File "C:\Python\Python352-32\lib\site-packages\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python\Python352-32\lib\site-packages\requests\adapters.py", line 473, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', TimeoutError(10060, 'A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond', None, 10060, None))

**Comment by sevakmaheshr** [comment] 2017-04-22 09:55
I have the same issue. Please fix it soon.

**Comment by nishad** [comment] 2017-05-06 03:33
Duplicate of https://github.com/nishad/udemy-dl/issues/207

**Closed by nishad** 2017-05-06 03:33 UTC
Labels: duplicate
