### ISSUE TITLE
[CRITICAL-285] Skipped. Expected quality not found!

### ISSUE THREAD

**Issue by shaanpatel** [nishad/udemy-dl#232] opened 2017-07-06 07:13 UTC
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **X.X.X**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [ ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

Been facing this problem since the past 3 days. Was able to download content before. Any insight on why I'm facing this problem?

<img width="618" alt="screen shot 2017-07-06 at 12 35 45 pm" src="https://user-images.githubusercontent.com/14263784/27899628-a2a19722-6248-11e7-9396-80e5803b2949.png">

**Comment by pavelkalin** [comment] 2017-07-06 07:24
I also face the same problem

Here is excerpt
Getting course data: 2.60% [=-------------------] [CRITICAL-285] Skipped. Expected quality not found!
Getting course data: 5.19% [=-------------------] [CRITICAL-285] Skipped. Expected quality not found!
Getting course data: 6.49% [=-------------------] [CRITICAL-285] Skipped. Expected quality not found!

**Comment by ocuil** [comment] 2017-07-06 07:56
Me too !!!
Getting course data: 2.00% [--------------------] [CRITICAL-285] Skipped. Expected quality not found!
Getting course data: 3.00% [=-------------------] [CRITICAL-285] Skipped. Expected quality not found!
Getting course data: 4.00% [=-------------------] [CRITICAL-285] Skipped. Expected quality not found!
Getting course data: 5.00% [=-------------------] [CRITICAL-285] Skipped. Expected quality not found!
Getting course data: 7.00% [=-------------------] [CRITICAL-285] Skipped. Expected quality not found!

**Comment by nishad** [comment] 2017-07-06 08:48
Duplicate of https://github.com/nishad/udemy-dl/issues/231

**Closed by nishad** 2017-07-06 08:48 UTC
Labels: duplicate
