### ISSUE TITLE
[PROPOSAL] Support for Udemy business accounts

### ISSUE THREAD

**Issue by kumarldh** [nishad/udemy-dl#191] opened 2017-02-14 15:29 UTC
Udemy business accounts do not have www in the URL. They are usually https://**businessname**.udemy.com. Support for this can be easily added by modifying the regex checks here: https://github.com/nishad/udemy-dl/blob/master/src/udemy_dl/udemy_dl.py#L847
I have done this for my account and have tested it. Can the author look at it this proposal? Thanks!

**Comment by tmatet** [comment] 2017-03-06 19:19
Hi, could you please explain how to modify, to download courses from business udemy?

**Comment by kumarldh** [comment] 2017-03-07 02:58
@tmatet, I assume that you know how to program in Python, even beginner level knowledge will work. I modified the source code for this app to accommodate the url for out business account. Look at https://github.com/nishad/udemy-dl/blob/master/src/udemy_dl/udemy_dl.py#L847 and you will be able to do it.

**Comment by egadgetjnr** [comment] 2017-03-07 03:28
@kumarldh, have you created a fork for your changes?
It would be handy to get this in as a PR as this has been requested for some time now but @nishad or any of the other contributors have a business account to develop and test.

**Comment by tmatet** [comment] 2017-03-07 06:14
@kumarldh yes sure, I modified the code but it's not working, that is why I asked your help. In the last version it's in line 764 if I'm not wrong.
t```
ry:
        if 'udemy.com/draft/' in link_args:
            link = re.search(r'(*\.udemy\.com/draft/.*?)/', link_args + '/').group(1)
        else:
            link = re.search(r'(*\.udemy\.com/.*?)/', link_args + '/').group(1)
    except AttributeError:
        logger.error('Please follow right url format.\nEx. https://www.udemy.com/COURSE-NAME, https://www.udemy.com/draft/COURSE-ID')
        sys.exit(1)
```

**Comment by kumarldh** [comment] 2017-03-07 06:19
@egadgetjnr IMO, the URL should be passed as option and if not passed then default value should be www.udemy.com. If you want me to fork and then create a PR, it would take some time. I can do that but by weekend. 

@tmatet I simply used `https://businessname.udemy.com` instead of `*.udemy.com`, I was impatient and needed to download something. :-)

**Comment by kumarldh** [comment] 2017-03-07 06:19
I closed it by mistake, re-opening this

**Comment by tmatet** [comment] 2017-03-07 06:34
Hi, thank you! This is fine, but I still have an error, 
`[INFO-107] Trying to log in ...
[ERROR-127] Couldn't fetch token!
`

**Comment by kumarldh** [comment] 2017-03-07 06:37
Well...can you check if your user pass is correct, can't help without looking at code.

**Comment by tmatet** [comment] 2017-03-07 07:14
Yes, I'm tying with the same as in browser. Maybe there is some specific login process for my company.

**Comment by kumarldh** [comment] 2017-03-14 11:17
@egadgetjnr I propose following regex to take care of subdomains 
* At line 849 `(https://.*?\.udemy\.com/draft/.*?)` 
* At line 851 `(https://.*?\.udemy\.com/.*?)`  

This should help in getting the URL. Do I still need to create a PR? Do you want a lazy guy to work? :grimacing:

**Comment by egadgetjnr** [comment] 2017-03-15 06:25
@kumarldh, I've spent the last couple of days working on this and unfortunately I don't think this is the only thing that needs to happen. It looks like it's harder to get the course ID if you don't use the proper business URL login method.

I'll continue looking into this, but if you've got any idea that would be helpful.

**Comment by kumarldh** [comment] 2017-03-15 06:37
If the authentication is a matter then yes, the problem gets harder. My organisation uses a third party tool to manage SSO which takes my to a centralised site which then takes me to Udemy. I know this sounds stupid but that's how corporations work. I could test this by just changing the regex pattern for my organisation.

**Comment by nishad** [comment] 2017-03-16 08:30
This is a duplicate of https://github.com/nishad/udemy-dl/issues/65 and explained in https://github.com/nishad/udemy-dl/issues/65#issuecomment-202492772. However other than the external login, udemy business accounts are own by the business not the end user, so that violates the ethical aspect of this tool.

**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.

**Closed by nishad** 2017-03-16 08:30 UTC

**Comment by kumarldh** [comment] 2017-03-16 09:34
>udemy business accounts are own by the business not the end user, so that violates the ethical aspect of this tool.

Agreed. Plus I could do it for my account with said regex change. Thanks!
