### ISSUE TITLE
[PROPOSAL] support subdomains

### ISSUE THREAD

**Issue by zabbal** [nishad/udemy-dl#81] opened 2016-04-02 20:40 UTC
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

Right now only main udemy domain seems to be supported - trying to download from https://st-mooc.udemy.com/nfc-online-course-with-hands-on-exercises/learn/v4/t/lecture/... for instance leads to following error:
```
...udemy_dl.py, line 606, in main
    link = re.search(r'(https://www.udemy.com/.*?)/', link_args + '/').group(1)
AttributeError: 'NoneType' object has no attribute 'group'
Would be nice if url regexp could be adopted to work on arbitrary subdomains *.udemy.com
``

**Comment by nishad** [comment] 2016-04-02 20:42
Seems like a Duplicate of https://github.com/nishad/udemy-dl/issues/65, if it is a duplicate, please close this thread and continue commenting in https://github.com/nishad/udemy-dl/issues/65

**Closed** 2016-04-02 20:45 UTC
