### ISSUE TITLE
[QUESTION] ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

### ISSUE THREAD

**Issue by iamsmith41** [nishad/udemy-dl#220] opened 2017-05-19 10:01 UTC
Version : udemy-dl 0.2.1
Using Ubuntu 17.04 x64 desktop version.

In raising this issue, I confirm the following (please check boxes, eg [X]):

[x ] I have read and understood the contributors guide.
[x ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
[x ] I have checked that the issue I'm posting isn't already reported.
[x ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in closed issues and in opened issues
[x ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.
My familiarity with the project is as follows (check one, eg [X]):

[ ] I have never used the project.
[x ] I have used the project briefly.
[ ] I have used the project extensively, but have not contributed previously.
[ ] I am an active contributor to the project.
[ ] If the project maintainer has any additional requirements, they will be listed here.

No additional requirements.

---

Below error occurs frequently for almost every course. 
One thing that I observed is it occurs just after this point: 

`Downloading attached files`

That is it keeps waiting at this downloading attached files and fails with the error below.

I restart the course to download and everything goes fine, downloading videos and attached files, and then suddenly it will wait at anyone attached file and fails.

```
Downloading: 100.00% [==============================] Done

Downloading attached files

[ERROR-61] Exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/__main__.py", line 8, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 947, in main
    save_links, safe_file_names, just_list, output_dest, dir_use_course_title)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 803, in udemy_dl
    get_data(directory, filename, data_url, data_type, attached_info, caption_list)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 696, in get_data
    get_attached_file(file_dir, attached_info)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 571, in get_attached_file
    attached_json = session.get(attached_url).json()
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 91, in get
    return self.session.get(url, headers=self.headers)
  File "/home/ad/.local/lib/python2.7/site-packages/requests/sessions.py", line 531, in get
    return self.request('GET', url, **kwargs)
  File "/home/ad/.local/lib/python2.7/site-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ad/.local/lib/python2.7/site-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/home/ad/.local/lib/python2.7/site-packages/requests/adapters.py", line 488, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))

```

Thanks to assist. It is taking so much time to again and again restart course.

**Comment by iamsmith41** [comment] 2017-05-21 01:53
Hi,

I just wanna know if we can do anything from our side or its purely server related?

**Comment by nishad** [comment] 2017-05-21 04:29
@iamsmith41, there is a new version of udemy-dl in Pypi than yours, and this is a duplicate of https://github.com/nishad/udemy-dl/issues/201

**Comment by iamsmith41** [comment] 2017-05-22 09:29
@nishad, #201 is about **KeyError: u'results** and #220 is about **('Connection aborted.', error(104, 'Connection reset by peer'))**

**Comment by iamsmith41** [comment] 2017-05-22 11:52
I have updated udemy-dl.
Now my version is udemy-dl 0.2.2-alpha

But still getting this error that I posted above -
`('Connection aborted.', error(104, 'Connection reset by peer'))`

**Comment by iamsmith41** [comment] 2017-05-22 15:01
As I posted above, I am getting this error only when its trying to download any attached file or article, also that is not fixed at which point means its totally random but its only at this point.

After updating my udemy-dl (0.2.2-alpha), same error:

```
**Downloading Article: 097 Advanced Python Modules FAQ**

[ERROR-61] Exception
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/__main__.py", line 8, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 947, in main
    save_links, safe_file_names, just_list, output_dest, dir_use_course_title)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 803, in udemy_dl
    get_data(directory, filename, data_url, data_type, attached_info, caption_list)
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 684, in get_data
    html_json = session.get(link).json()
  File "/usr/local/lib/python2.7/dist-packages/udemy_dl/udemy_dl.py", line 91, in get
    return self.session.get(url, headers=self.headers)
  File "/home/ad/.local/lib/python2.7/site-packages/requests/sessions.py", line 531, in get
    return self.request('GET', url, **kwargs)
  File "/home/ad/.local/lib/python2.7/site-packages/requests/sessions.py", line 518, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ad/.local/lib/python2.7/site-packages/requests/sessions.py", line 639, in send
    r = adapter.send(request, **kwargs)
  File "/home/ad/.local/lib/python2.7/site-packages/requests/adapters.py", line 488, in send
    raise ConnectionError(err, request=request)
ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
```
Previously also it was happening while downloading attached file, randomly at any point.
Here also error throwing while downloading the article.
But when I will restart the download it will successfully download that article/attached file where it failed previously and then continues to download videos and other stuffs and then again suddenly same thing will happen randomly at any point.

I observed that it is not failing at a sudden at these points but waits at these points for few seconds as if trying to renegotiate something or verifying something or initialising whole handshake, I don't know, and then fails with this error.

It has been really tough for me to sit and restart downloads multiple times for a single course because it throws this error frequently. Not downloaded a single course without sitting near the pc.

Kindly assist. Thanks.

**Comment by iamsmith41** [comment] 2017-05-25 04:31
Hi,
Please assist.
Thanks.

**Comment by nishad** [comment] 2017-05-29 20:32
**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.

**Closed by nishad** 2017-05-29 20:32 UTC
Labels: invalid, Unacceptable

**Comment by iamsmith41** [comment] 2017-05-31 03:57
Can it be reopened now?
