### ISSUE TITLE
[BUG] Failed to get course ID

### ISSUE THREAD

**Issue by renishkhunt** [nishad/udemy-dl#48] opened 2016-03-04 17:13 UTC
Hi, Thanks for this script it's really helpful for me 

i got a error "Failed to get course ID" because of Udemy his layouts. please help me to resolved this

Thanks

**Comment by yakloin** [comment] 2016-03-06 10:08
I'm also receiving the same error on all courses.

"Failed to get course ID"

**Comment by mukhlesur-millon** [comment] 2016-03-06 10:44
an upgrade may fix the problem
`python -m pip install --upgrade https://github.com/nishad/udemy-dl/zipball/master`
if it doesn't, please comment the course url

**Comment by yakloin** [comment] 2016-03-06 11:41
It made no change. 

Still receive "Failed to get course ID"

**Comment by mukhlesur-millon** [comment] 2016-03-06 11:43
course url?
i have issue.

**Comment by yakloin** [comment] 2016-03-06 11:44
learn-linux-in-5-days

**Comment by mukhlesur-millon** [comment] 2016-03-06 11:48
it is paid course so i cant test it. may be you haven't enter the full url..
usage:
`python3 -m udemy_dl https://www.udemy.com/learn-linux-in-5-days`

**Comment by yakloin** [comment] 2016-03-06 11:55
python -m udemy_dl -u xxxxxxxxxxxxxx -p xxxxxxxxx https://www.udemy.com/learn-linux-in-5-days

logs in ok but then same error message "Failed to get course ID"

**Comment by yakloin** [comment] 2016-03-06 11:56
Failing on all my paid courses not just this one.

**Comment by mukhlesur-millon** [comment] 2016-03-06 12:06
did you buy it?

**Comment by yakloin** [comment] 2016-03-06 12:07
Yes and the rest of my paid courses.

**Comment by yakloin** [comment] 2016-03-06 12:09
Link free course that is working and I will attempt that.

**Comment by mukhlesur-millon** [comment] 2016-03-06 12:15
you can use https://gist.github.com to me your saved html page of your course.

**Comment by mukhlesur-millon** [comment] 2016-03-06 12:18
sorry i have noticed it you have write python instead of python3
`python3 -m udemy_dl -u xxxxxxxxxxxxxx -p xxxxxxxxx https://www.udemy.com/learn-linux-in-5-days`

**Comment by yakloin** [comment] 2016-03-06 12:28
fails when run python3

python3 : The term 'python3' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

**Comment by renishkhunt** [comment] 2016-03-06 17:40
Hey yakloin, i still getting same error how you can resolved. i update my script with this command

python -m pip install --upgrade https://github.com/nishad/udemy-dl/zipball/master


still i getting same error. i try to download this course

https://www.udemy.com/mobile-game-development-with-unity-3d

Please help

**Comment by nishad** [comment] 2016-03-06 17:50
I couldn't reproduce this error, so I guess it is not a bug.

**Comment by renishkhunt** [comment] 2016-03-06 18:02
suddenly stopped working i upgrade it but then after it's not working. if you need my account details i can give you. really it's not working for me. 

i try all solution that you posted on same old question but still i getting same error.

**Comment by renishkhunt** [comment] 2016-03-06 18:09
please see this screenshot of error that i getting/
![giterror](https://cloud.githubusercontent.com/assets/6428915/13555971/89babaaa-e3f4-11e5-88f4-99ee3b972725.png)

**Comment by nishad** [comment] 2016-03-06 18:10
So far since it is impossible to reproduce this error, I don't consider this as a general bug. If there are some changes with udemy website, probably we will be getting more issues similiar to this. In that case, I'll try to fix if I could reproduce the error. Till then continue learning your courses online.

**Comment by renishkhunt** [comment] 2016-03-06 19:05
Hi Nishad, it's not working with "renish.khunt@yahoo.com" email address i try to my another email address with purchasing the free course and it's working. you have any idea why it's stopped working for "renish.khunt@yahoo.com" account?

**Comment by yakloin** [comment] 2016-03-06 21:39
HI Nishad, Maybe it's due to a change on the Udemy site. Can provide my login details for you to test against paid course.

**Comment by nishad** [comment] 2016-03-10 23:55
It is fixed with https://github.com/nishad/udemy-dl/commit/ee6ecab864fc0adb5eb46d92f6a67ad370e58d27, you can try again with the latest development version.

**Closed by nishad** 2016-03-10 23:55 UTC
Labels: bug, Unknown

**Comment by yakloin** [comment] 2016-03-11 15:58
Thanks Nishad. Slight confused, I've downloaded the new version, do I just replace udemy-dl with the new file?

**Comment by nishad** [comment] 2016-03-11 16:00
Instructions are here : https://github.com/nishad/udemy-dl/wiki/Installing-development-version

**Comment by yakloin** [comment] 2016-03-11 18:17
Thanks Nishad, installed ok. However, course still fails.

```
PS C:\Users\xxxx\AppData\Local\Programs\Python\Python35> ./python -m udemy_dl https://www.udemy.com/learn-linux-in-5-days
Username / Email : xxxxxxxxxxxxxxxxx
Password :
Downloading to: C:\Users\xxxx\AppData\Local\Programs\Python\Python35\learn-linux-in-5-days

Trying to log in ... and we're done.
Traceback (most recent call last):
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python35\lib\site-packages\udemy_dl\__main__.py", line 8, in <module>
    main()
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python35\lib\site-packages\udemy_dl\udemy_dl.py", line 546, in main
    udemy_dl(username, password, link, lecture_start, lecture_end, save_links, safe_file_names, just_list, output_dest)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python35\lib\site-packages\udemy_dl\udemy_dl.py", line 403, in udemy_dl
    course_id = get_course_id(course_link)
  File "C:\Users\xxxx\AppData\Local\Programs\Python\Python35\lib\site-packages\udemy_dl\udemy_dl.py", line 102, in get_course_id
    if debug:
NameError: name 'debug' is not defined
```

**Comment by nishad** [comment] 2016-03-11 18:31
I pushed a new commit https://github.com/nishad/udemy-dl/commit/64de7bb10bdd6707281b071488faa691daba14cb, this will resolve the error. Please upgrade again and try.

**Comment by yakloin** [comment] 2016-03-11 18:34
Early signs are great, working now. Will report at the end. Thank you so much!!

**Comment by yakloin** [comment] 2016-03-12 01:46
Yes it worked well, all videos downloaded. I'm not sure why, but it downloaded some of the PDF files and left others. I can easily manually download but any suggestion why it did not download all PDF files?

**Comment by renishkhunt** [comment] 2016-03-12 05:09
Thank you so much nishad. it's work for me. Thanks a lot :)

**Comment by developsoft** [comment] 2016-03-28 18:54
Hi everybody...I got the same error "Failed to get the course ID" with the latest version in windows. Thanks in advance if someone can help me...

**Comment by nishad** [comment] 2016-03-28 18:56
This is a closed thread, find any open issue similar to yours and comment there.

**Comment by hirowatari** [comment] 2016-04-06 21:13
Using the development version fixed the issue for me.  Thank you.

**Comment by darkhost21** [comment] 2016-04-09 18:11
@hirowatari .. how do you make it to work? what was the steps?

**Comment by rater1994** [comment] 2016-05-24 17:47
Hello, I try to solve  "Failed to get course ID"  I use udemy version 2.0.1. I try to edit udemy-dl.py but isn't work. I don't know what I have to do. Please someone help me or tell me please what I need to edit where I need to make edit. Please help me.  or contact me a gmail: athauf94@gmail.com Please.! Thank YOU.

**Comment by nishad** [comment] 2016-05-26 07:14
@rater1994, there isn't any 2.0.1 version for `udemy-dl`. You can try to install the latest development version, as explained in https://github.com/nishad/udemy-dl/wiki/Installing-development-version

**Comment by rater1994** [comment] 2016-05-29 16:07
@nishad Thank you for answer but I still have a problem. I install that version from : https://github.com/nishad/udemy-dl/wiki/Installing-development-version but after I try to download  I recevive  [ERROR-678] Not a downloadable course. Why? :(

**Comment by tobias-p** [comment] 2016-05-29 20:00
@rater1994 here's the answer to your question: https://github.com/nishad/udemy-dl/issues/78#issuecomment-204718889

**Comment by rater1994** [comment] 2016-05-30 07:26
@tobias-p  Thank you for answer. But I still have that problem not work. I try 10+ and don't work.. :( .To know it's ok If I use this command : python -m udemy_dl and link (with preview course) ?

**Comment by tobias-p** [comment] 2016-05-30 07:38
as far as I know the udemy-dl doesnt download previews of a course. But can't really say that because I just downloaded courses I bought.

**Comment by rater1994** [comment] 2016-05-30 07:40
Aa you buy? the course...I don't wanna pay:))

**Comment by egadgetjnr** [comment] 2016-05-30 08:09
There is a way to fix this, send me your username and password and credit
card number and what courses you want and I'll sort it for you.

Alternatively, don't be a pirate/cheapskate and buy the course. Otherwise,
move along...

I'm sorry, but I'm sick of seeing people wanting everything for nothing
when the trainers that make the courses put so much time and money into it.

**Comment by rater1994** [comment] 2016-05-30 08:17
Lol :))are you kidding me? Where I got this topic about udemy-dl It's from forum where title it's  "Free course udemy". I don't give money for all becouse I know i can get free.And don't tell me about sick when I can get free. So If  you wanna help me do it if no please take you'r time to do another job's.Thank you.

**Comment by egadgetjnr** [comment] 2016-05-30 08:34
Can't help you do something that's not possible..... Udemy changed their
API to stop pirates.

Why don't you message Udemy to ask them to change their API so you can get
paid courses for free?

Good luck.

**Comment by rater1994** [comment] 2016-05-30 13:17
Oo I will try them I will say where I get Ideea thank you :)

**Comment by tobias-p** [comment] 2016-05-30 13:35
Good luck in finding software which enables you pirating courses while keylogging everything you are typing at your pc ;)

**Comment by rater1994** [comment] 2016-05-30 13:37
Thank you.

**Comment by Manblock** [comment] 2016-08-15 16:54
[INFO-127] TRYING RO LOG IN...
[INFO-157] LOGIN SUCCESS
[ERROR-171] PLEASE ENROLL THIS COURSE
i have an error **([ERROR-171] PLEASE ENROLL THIS COURSE)** PLEASE HELP..
@nishad 
@developsoft

**Comment by francyfre** [comment] 2017-04-19 08:01
i have this problem to download now! 
somebody can help me please? 

![errorudemydl](https://cloud.githubusercontent.com/assets/20769713/25169396/2c746320-24e7-11e7-8cf0-71ca4462ede6.jpg)
