### ISSUE TITLE
[BUG] Failed to Get Couse ID

### ISSUE THREAD

**Issue by yoonwaiyan** [nishad/udemy-dl#100] opened 2016-04-22 12:11 UTC
**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

---

this issue is related to #99 with proper formatting as requested.

I want to download a course from Udemy today but failed with an error: Failed to get course ID.

How to replicate it:
1. Upgraded `udemy-dl` by using `pip install --upgrade udemy-dl` to make sure newest version is being used.
2. Use this command to download a Hadoop course: `udemy-dl https://www.udemy.com/hadoop-tutorial`. Insert Udemy login email and password.
3. Terminal prompts this message: 

> Downloading to: /Users/yoonwaiyan/Documents/workspace/hadoop-tutorial
>
> Failed to get course ID

Suspecting it's because Udemy has updated their front end.

**Comment by nishad** [comment] 2016-04-22 17:03
@yoonwaiyan , At present `udemy-dl` doesn't got any stable PyPi release after `0.2.0`. Current development release is `0.2.1-beta`.

You may need to install current development version to resolve this issue. Please refer this wiki page for instructions to install development version (https://github.com/nishad/udemy-dl/wiki/Installing-development-version).

If it is not working after the upgrade please post the output of `udmey-dl -v`.

This issue is a duplicate of https://github.com/nishad/udemy-dl/issues/61.

**Comment by meesterp** [comment] 2016-04-22 19:26
I'm on Windows (Win10x64) and am also getting this error. I downloaded the latest version for Windows (udemy-dl-win-2.0.1.zip from this url: [(https://github.com/nishad/udemy-dl-windows/releases/tag/v2.0.1)]) and seem to be unable to download any course :(
`E:\Udemy\downloader\udemy-dl-win>udemy-dl.exe -u xxxxxx -p xxxxxx https://www.udemy.com/csharpbasics --lecture-start 2 --lecture-end 116
Downloading to: E:\Udemy\downloader\udemy-dl-win\csharpbasics

Failed to get course ID

E:\Udemy\downloader\udemy-dl-win>`

When I execute udemy-dl -v I get this output:
`E:\Udemy\downloader\udemy-dl-win>udemy-dl.exe -v
udemy-dl.exe 2.0.1`
Which according to a comment by nishad in another thread does not exist ??

What am I missing ?

**Comment by nishad** [comment] 2016-04-22 19:33
@meesterp, `udemy-dl-windows` is another project. Unfortunately this issue tracker is only for `udemy-dl` and cannot answer queries or resolve issues related to any other project. Sorry for the inconvenience.

**Comment by meesterp** [comment] 2016-04-22 19:45
different project maybe, but it says "udemy-dl for Windows", which is still udemy-dl.
There's no place to post issues with `udemy-dl-win` ?

**Comment by nishad** [comment] 2016-04-22 20:14
Coca-Cola is 90% water, but that doesn't make it water.  The Same logic is applicable for `udemy-dl-windows` and `udemy-dl`.

`udemy-dl-windows` only provide binaries of https://pypi.python.org/pypi/udemy-dl.   

It is tough to manage and resolve issues from a group of abusive and bullying users, who doesn't get any basic idea what an open-source project is. That is the main reason for deactivating issue tracker for `udemy-dl-windows` project. 

There is not plan to support `udemy-dl-windows` users here.

**Comment by dhitiadeveloper** [comment] 2016-04-28 08:45
i have installed current development version to resolve this issue on my mac use `sudo pip install --upgrade https://github.com/nishad/udemy-dl/zipball/master
` unfortunately i got below problems once i check the version use `udmey-dl -v.` it's still udemy-dl 0.2.0. please your kindly to assist me.

![screen shot 2016-04-28 at 3 39 52 pm](https://cloud.githubusercontent.com/assets/16545562/14880130/80cf4e7e-0d57-11e6-8297-15993ef6ade0.png)

**Comment by nishad** [comment] 2016-04-28 08:55
try a complete uninstall and try the install command
```bash
sudo pip uninstall -y udemy-dl 
sudo pip uninstall -y -r https://raw.githubusercontent.com/nishad/udemy-dl/master/requirements.txt
```
then
```bash
sudo pip install https://github.com/nishad/udemy-dl/zipball/master
```

**Comment by morphdhitia** [comment] 2016-04-28 09:21
Wow, it works perfectly. anyway i try to download the videos and appears message like below..
my question is where should i put --use-ffmpeg as well as there is aria2c not found. does it affect to my videos? 
![screen shot 2016-04-28 at 4 11 36 pm](https://cloud.githubusercontent.com/assets/16545562/14881143/eb4ef2d6-0d5c-11e6-84b4-5cb3950f22c6.png)

**Comment by nishad** [comment] 2016-04-28 09:30
@morphdhitia I assume you are using mac, in that case you can get latest ffmpeg binary from http://www.ffmpegmac.net/.

You can copy `ffmpeg` to `/usr/local/bin/` try `ffmpeg -version` to ensure that it is properly installed.

You can also install `aria2c` via `brew` with this command `brew install aria2`

If `brew` is not available then you can get the latest binaries for `aria2` from https://github.com/aria2/aria2/releases/latest

use   `--use-ffmpeg` before the link of the course like `udemy-dl --use-ffmpeg LINK`

**Comment by morphdhitia** [comment] 2016-04-28 09:43
@nishad thank you so much.. it works amazingly.

**Comment by GabrielXpz** [comment] 2016-04-28 21:43
I`m currently getting this error.... 

Downloading to: /Users/Test/angular-2-master-class-with-alejandro-rangel

Trying to log in ... and we're done.
Searching course id... Found: 769390
ERROR: Not a downloadable course.
MBP-de-Test:~ gabrielrodrigues$

**Comment by davecrouse** [comment] 2016-04-29 04:14
hi.,

I can't install and my video very bad quality. How can i fix it? thanks


> nishad

I assume you are using mac, in that case you can get latest ffmpeg binary from http://www.ffmpegmac.net/.

You can copy ffmpeg to /usr/local/bin/ try ffmpeg -version to ensure that it is properly installed.

You can also install aria2c via brew with this command brew install aria2

If brew is not available then you can get the latest binaries for aria2 from https://github.com/aria2/aria2/releases/latest

use --use-ffmpeg before the link of the course like udemy-dl --use-ffmpeg LINK

**Comment by yoonwaiyan** [comment] 2016-04-29 14:39
@nishad Thanks, I faced the same problem as @morphdhitia, but after re-installed it works now. I'm using builtin downloader, looks okay.

**Comment by bharken** [comment] 2016-04-30 21:35
@morphdhitia @nishad Is there a difference between ffmpeg/aria2 and the built-in downloader? Just curious.

**Comment by nishad** [comment] 2016-04-30 21:37
Yes, there is. Thinking of creating a wiki page on that. Since I'm busy nowadays, if there's any volunteer please come forward.

**Comment by bharken** [comment] 2016-04-30 21:50
Thanks for the quick response! I'll try it out later.
I'd love to volunteer but I'm not good at it. Hope someone will. Btw, thanks for this project. It helped us a lot.

**Comment by IDSFN** [comment] 2016-04-30 21:55
@nishad Hi ;), i have the same problem @GabrielXpz had !
```
Trying to log in ... and we're done.
Searching course id... Found: 769390
ERROR: Not a downloadable course.
```
What's wrong ?

**Comment by nishad** [comment] 2016-04-30 22:09
@IDSFN, @GabrielXpz Hope you've seen that the title of this issue it is **Failed to Get Course ID** which is not related to your comment.

Your issue is already answered a couple of times, (https://github.com/nishad/udemy-dl/issues?utf8=%E2%9C%93&q=Not+a+Downloadable+Course)

Please be reasonable, and there is a checklist for every issues

- [x] I have checked that the issue I'm posting isn't already reported.
- [x] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)

By posting any non-related queries in an opened thread, you are messing up the whole thing.

**Comment by nishad** [comment] 2016-05-05 10:21
Fixed with v0.2.1. Follow steps in https://github.com/nishad/udemy-dl/blob/master/README.md#update to update.

**Closed by nishad** 2016-05-05 10:21 UTC
Labels: bug, duplicate

**Comment by scropion86** [comment] 2016-05-25 06:15
hi

using v0.2.1 and same error `Failed to get course ID`
here is the Course Link `https://www.udemy.com/html-and-css-for-beginners-crash-course-learn-fast-easy/`

**Comment by nishad** [comment] 2016-05-25 06:54
@scropion86, you can use `--debug` and post the debug files.

**Comment by trikyas** [comment] 2017-08-27 08:03
@nishad Thank you!!!
