### ISSUE TITLE
[PROPOSAL] Add support to download from https://citigroup.udemy.com/

### ISSUE THREAD

**Issue by vijendra4** [nishad/udemy-dl#222] opened 2017-06-05 12:16 UTC
Currently when I try to download from https://citigroup.udemy.com/ with the following command

` python3 -m udemy_dl -s https://citigroup.udemy.com/deep-learning-with-tensorflow`

I get the error -

```
[ERROR-770] Please follow right url format.
Ex. https://www.udemy.com/COURSE-NAME, https://www.udemy.com/draft/COURSE-ID
```

Can we please try to add support to downloading from this URL?

**Comment by ferrazoli** [comment] 2017-06-09 22:41
That's the URL format of Udemy for Business, in other words anything.udemy.com won't work.

**Comment by i5uhail** [comment] 2017-06-16 05:56
It would have been awesome if it did work. 👍

**Comment by nishad** [comment] 2017-06-16 10:48
This is a duplicate of https://github.com/nishad/udemy-dl/issues/65 and explained in https://github.com/nishad/udemy-dl/issues/65#issuecomment-202492772. 

Most of the udemy business account uses external authentication other than the standard udemy.com login. Which cannot be supported without access to all these accounts or as a maintainer I am not in a position to respond to all queries related to various login issues.

However other than the external login, udemy business accounts are own by the business not the end user, so that violates the ethical aspect of this tool.

**All issues should contain mandatory check lists, version number and proper prefix for the subject line. Issues reported without checklists, version or without proper prefix will be closed or ignored.**

Due to this policy I'm closing this thread, you can request to reopen this issue after making sufficient changes.

**Closed by nishad** 2017-06-16 10:48 UTC
