### ISSUE TITLE
[BUG] [CRITICAL-268] Skipped. Expected quality not found!

### ISSUE THREAD

**Issue by sbp-lotus** [nishad/udemy-dl#210] opened 2017-04-17 07:08 UTC
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Version : udemy-dl 0.2.2-alpha

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X ] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [X ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X ] I have checked that the issue I'm posting isn't already reported.
- [X ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [ X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [X ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---
Hello, 
please help me to resolve it,throwing error when I am trying to download it. It is for video only if any text file then it will download successfully.
Getting course data: 1.85% [--------------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 2.78% [=-------------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 3.70% [=-------------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 5.56% [=-------------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 6.48% [=-------------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 7.41% [=-------------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 8.33% [==------------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 9.26% [==------------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 10.19% [==------------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 11.11% [==------------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 12.04% [==------------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 12.96% [===-----------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 13.89% [===-----------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 14.81% [===-----------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 15.74% [===-----------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 16.67% [===-----------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 17.59% [====----------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 18.52% [====----------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 19.44% [====----------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 20.37% [====----------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 22.22% [====----------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 24.07% [=====---------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 25.00% [=====---------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 25.93% [=====---------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 26.85% [=====---------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 27.78% [======--------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 28.70% [======--------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 29.63% [======--------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 30.56% [======--------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 31.48% [======--------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 32.41% [======--------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 33.33% [=======-------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 34.26% [=======-------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 36.11% [=======-------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 37.96% [========------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 38.89% [========------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 39.81% [========------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 40.74% [========------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 41.67% [========------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 42.59% [=========-----------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 43.52% [=========-----------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 45.37% [=========-----------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 47.22% [=========-----------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 48.15% [==========----------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 49.07% [==========----------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 50.00% [==========----------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 50.93% [==========----------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 51.85% [==========----------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 52.78% [===========---------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 53.70% [===========---------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 54.63% [===========---------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 55.56% [===========---------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 56.48% [===========---------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 57.41% [===========---------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 58.33% [============--------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 59.26% [============--------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 60.19% [============--------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 62.04% [============--------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 63.89% [=============-------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 64.81% [=============-------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 65.74% [=============-------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 66.67% [=============-------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 67.59% [==============------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 68.52% [==============------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 69.44% [==============------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 70.37% [==============------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 71.30% [==============------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 72.22% [==============------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 73.15% [===============-----] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 74.07% [===============-----] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 75.00% [===============-----] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 76.85% [===============-----] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 78.70% [================----] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 79.63% [================----] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 80.56% [================----] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 81.48% [================----] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 82.41% [================----] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 83.33% [=================---] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 84.26% [=================---] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 85.19% [=================---] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 86.11% [=================---] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 87.04% [=================---] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 87.96% [==================--] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 89.81% [==================--] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 92.59% [===================-] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 93.52% [===================-] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 94.44% [===================-] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 95.37% [===================-] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 97.22% [===================-] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 98.15% [====================] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 100.00% [====================] Done
[CRITICAL-268] Skipped. Expected quality not found!

**Comment by seanwhe** [comment] 2017-04-18 08:27
Finding the same issue.
Was working just find and then today failed.

Does not matter which way it was installed. Last version installed by
sudo pip install https://github.com/nishad/udemy-dl/zipball/master

udemy-dl -v
udemy-dl 0.2.2-alpha

[INFO-132] Trying to log in ...
[INFO-161] Login success.
[INFO-193] Found course id: 628796
[INFO-205] Found course title: Mastering Ansible
Getting course data: 1.52% [--------------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 3.03% [=-------------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 6.06% [=-------------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 7.58% [==------------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 10.61% [==------------------] [CRITICAL-268] Skipped. Expected quality not found!

Text files do not display the same. Error is being reported only for video resources.

**Comment by smeggingsmegger** [comment] 2017-04-18 14:38
This is a duplicate of #207 

My fix here: https://github.com/nishad/udemy-dl/pull/209

**Comment by sbp-lotus** [comment] 2017-04-19 10:51
Can you please fix the same with Python3.5. It is not working with this version

**Comment by nishad** [comment] 2017-05-06 03:33
Duplicate of https://github.com/nishad/udemy-dl/issues/207

**Closed by nishad** 2017-05-06 03:33 UTC
Labels: duplicate
