### ISSUE TITLE
[PROPOSAL] [ERROR-1198] Traceback (most recent call last)

### ISSUE THREAD

**Issue by iamsmith41** [nishad/udemy-dl#198] opened 2017-03-12 22:24 UTC
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **udemy-dl 2.1.2**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [X] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [X] I have checked that the issue I'm posting isn't already reported.
- [X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

D:\Udemy\dist>udemy-dl.exe -u myemail@company.com -p 123456789 https://www.udemy.com/mastering-ansible/
[INFO-884] Downloading to: D:\Udemy\dist\mastering-ansible

[INFO-127] Trying to log in ...
[INFO-157] Login success.
[INFO-189] Found course id: 628796
[ERROR-1198] Traceback (most recent call last):
  File "<string>", line 889, in <module>
  File "<string>", line 886, in main
  File "<string>", line 705, in udemy_dl
  File "<string>", line 382, in get_data_links
KeyError: u'results'
None
udemy_dl returned -1

What I am seeing is -

the format supported by udemy-dl is :   https://www.udemy.com/course_name
But I am a company worker and by company end I have been provided access to all courses for free. My URL to learn them is -   https://company.udemy.com  and not   https://www.udemy.com

Now I compared the "My Courses" field at both URLs and found that the courses that are free to me at https://company.udemy.com/course_name, the same is asking me to purchase (not free) on https://www.udemy.com/course_name ( in fact there are no courses at https://www.udemy.com under "My Courses" field bcz I have not added any at this URL as I use company one, https://company.udemy.com, where I have many). Means both URLs are not replicating for the same account. They are independent to each other.

I signed in to both places with the same account. 
No SSO is there as I had to login separately at both places with the same account.

So how to proceed to download courses which are free to me at one and not on other?
Is there a way to use https://company.udemy.com/course_name  in command line?

Thanks.

This is my observation and if there is any other issue, then let me know how to proceed.

**Comment by egadgetjnr** [comment] 2017-03-13 00:30
@iamsmith41 , this has already been logged in #191. It is something that is currently been looked at. If I get some time, I'll work on a development branch of this so that you can give it a go. 
It's quite hard for @nishad to test as he does not have access to company accounts. 
I'm currently looking into getting one however for myself so that I can attempt to get this to work for alot of the users of udemy-dl.

**Comment by iamsmith41** [comment] 2017-03-13 04:46
OK Thanks.
For now, is there any way without manual task?

**Comment by egadgetjnr** [comment] 2017-03-13 10:27
@iamsmith41 Let me see what I can do..

In the meantime, can you please close this issue as it's a duplicate of an existing issue #191. Just comment/follow that one for when progress has been made.

**Comment by nishad** [comment] 2017-03-16 08:34
Duplicate of https://github.com/nishad/udemy-dl/issues/65, please continue the discussion in https://github.com/nishad/udemy-dl/issues/65

**Closed by nishad** 2017-03-16 08:34 UTC
