### ISSUE TITLE
[CRITICAL-268] Skipped. Expected quality not found!

### ISSUE THREAD

**Issue by ironbits** [nishad/udemy-dl#216] opened 2017-04-28 22:28 UTC
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Version : udemy-dl 0.2.2-alpha

Getting course data: 1.14% [--------------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 3.41% [=-------------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 4.55% [=-------------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 5.68% [=-------------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 6.82% [=-------------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 7.95% [==------------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 9.09% [==------------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 11.36% [==------------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 12.50% [===-----------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 17.05% [===-----------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 18.18% [====----------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 23.86% [=====---------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 26.14% [=====---------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 27.27% [=====---------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 30.68% [======--------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 31.82% [======--------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 32.95% [=======-------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 34.09% [=======-------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 36.36% [=======-------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 37.50% [========------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 38.64% [========------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 40.91% [========------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 42.05% [========------------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 44.32% [=========-----------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 45.45% [=========-----------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 46.59% [=========-----------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 48.86% [==========----------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 50.00% [==========----------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 51.14% [==========----------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 52.27% [==========----------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 53.41% [===========---------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 54.55% [===========---------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 55.68% [===========---------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 57.95% [============--------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 59.09% [============--------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 60.23% [============--------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 61.36% [============--------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 63.64% [=============-------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 64.77% [=============-------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 67.05% [=============-------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 68.18% [==============------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 69.32% [==============------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 70.45% [==============------] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 72.73% [===============-----] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 76.14% [===============-----] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 77.27% [===============-----] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 78.41% [================----] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 79.55% [================----] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 80.68% [================----] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 82.95% [=================---] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 84.09% [=================---] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 85.23% [=================---] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 86.36% [=================---] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 87.50% [==================--] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 88.64% [==================--] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 89.77% [==================--] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 90.91% [==================--] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 92.05% [==================--] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 93.18% [===================-] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 94.32% [===================-] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 95.45% [===================-] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 97.73% [====================] [CRITICAL-268] Skipped. Expected quality not found!
Getting course data: 100.00% [====================] Done

**Comment by AshikNesin** [comment] 2017-04-29 14:50
I'm also getting that issue :(

**Comment by black-byte** [comment] 2017-04-29 17:32
I have the same ;/ Any comment on that ?

**Comment by shundake** [comment] 2017-04-30 03:04
In this "Pull Request" we have a "fix" for now, from @smeggingsmegger 

https://github.com/nishad/udemy-dl/pull/209

**Comment by devaescasio** [comment] 2017-05-04 05:03
Hi,

Any fix update for Windows exe for this issue

**Comment by nishad** [comment] 2017-05-06 03:30
Duplicate of https://github.com/nishad/udemy-dl/issues/207

**Closed by nishad** 2017-05-06 03:30 UTC
Labels: duplicate

**Comment by AnmolTomer** [comment] 2017-05-12 15:28
pip install -U git+https://github.com/smeggingsmegger/udemy-dl.git@master
Run this. Make sure you have git installed and defined in path too.

**Comment by jkgatt** [comment] 2017-06-14 18:31
If you are getting the following error:
`DEPRECATION: Uninstalling a distutils installed project (six) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.`
when trying to run the following:
`pip install -U git+https://github.com/smeggingsmegger/udemy-dl.git@master`

Then you can run the following line instead:
`pip install --ignore-installed six -U git+https://github.com/smeggingsmegger/udemy-dl.git@master`

**Comment by MoCityMM** [comment] 2017-07-04 17:34
Critical-285 - couldn't find if anyone has submitted this one before. I am using the suggested 'python' 3.6 install with the 2 batch files, per the instructions Nishad provided. Worked great yesterday, now nada. Ran the update, nada. Tried Smeggingsmeggers suggestion, nada. It's a great tool! Just wished Udem allow downloads in general... like we are connected to that site all the time?..

**Comment by guibellotti** [comment] 2017-07-10 12:10
@MoCityMM Same thing here...
It used to be normal. i got solve it with issue #207 . But now its stopped working.
" [CRITICAL-285] Skipped. Expected quality not found! "
