### ISSUE TITLE
[Bug] [CRITICAL-407] Cannot download lecture "LECTURE NAME": "'NoneType' object has no attribute 'group'"

### ISSUE THREAD

**Issue by 7ang** [nishad/udemy-dl#142] opened 2016-08-26 13:05 UTC
Please prefix your issue with one of the following: [BUG], [PROPOSAL], [QUESTION].

Replace everything between stars with current version of your udemy-dl (output of udemy-dl -v):  
Version : **0.2.1**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [X ] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [X ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [ ] I have checked that the issue I'm posting isn't already reported.
- [ X] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [ X] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [ ] I have never used the project.
- [ X] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.
[Debug.zip](https://github.com/nishad/udemy-dl/files/439308/Debug.zip)

---

I really favor your project, but there are some scratch in this project (^O^)／

{udemy-dl -s --debug https://www.udemy.com/devslopes-ios10/        
[DEBUG-792] Debug mode is enabled, debug files will be saved in : 
/Users/shark

Username / Email : xt8441587zhen@163.com
Password : 
[INFO-833] Saving links to: /Users/shark/devslopes-ios10.txt

[INFO-107] Trying to log in ...
[INFO-137] Login success.
[DEBUG-157] Searching course id...
[INFO-169] Found course id: 892102
[DEBUG-348] Saving course_data...
Getting course data: 0.76% [--------------------] [DEBUG-181] Saving json source: 5475754
[DEBUG-224] Found list_m3u8
[CRITICAL-407] Cannot download lecture "Intro to Course": "'NoneType' object has no attribute 'group'"
Getting course data: 1.14% [--------------------] [DEBUG-181] Saving json source: 5490658
[DEBUG-224] Found list_m3u8
[CRITICAL-407] Cannot download lecture "Get 5000 worth of AMAZING graphics for FREE": "'NoneType' object has no attribute 'group'"
Getting course data: 1.52% [--------------------] [DEBUG-181] Saving json source: 5490672
Getting course data: 1.89% [--------------------] [DEBUG-181] Saving json source: 5414948
[DEBUG-224] Found list_m3u8
[CRITICAL-407] Cannot download lecture "Student success story": "'NoneType' object has no attribute 'group'"
Getting course data: 2.27% [--------------------] [DEBUG-181] Saving json source: 5396970
[DEBUG-224] Found list_m3u8
[CRITICAL-407] Cannot download lecture "Register as an Apple Developer": "'NoneType' object has no attribute 'group'"
Getting course data: 2.65% [=-------------------] [DEBUG-181] Saving json source: 5359274
[DEBUG-224] Found list_m3u8
[CRITICAL-407] Cannot download lecture "Downloading Xcode 8": "'NoneType' object has no attribute 'group'"
Getting course data: 3.03% [=-------------------] [DEBUG-181] Saving json source: 5396966
[DEBUG-224] Found list_m3u8
[CRITICAL-407] Cannot download lecture "Installing Xcode 8": "'NoneType' object has no attribute 'group'"
Getting course data: 3.41% [=-------------------] [DEBUG-181] Saving json source: 5396480
[DEBUG-224] Found list_m3u8
}

**Comment by 7ang** [comment] 2016-08-26 13:06
I find some resolution of this issue, but the link is invalid

**Comment by egadgetjnr** [comment] 2016-08-26 21:50
Please advise what version you're running.

**Comment by mrgerrm** [comment] 2016-08-26 23:11
I'm just now running into this same issue. Things were working normally about 1 hr ago.

**Comment by bharken** [comment] 2016-08-27 12:21
Try this one
https://github.com/nishad/udemy-dl/issues/125#issuecomment-234218643

**Comment by mrgerrm** [comment] 2016-08-28 06:32
Yeah I found that after I posted it and it's working. Thanks!

**Comment by nishad** [comment] 2016-08-28 19:03
This issue is a duplicate of https://github.com/nishad/udemy-dl/issues/125. This is already addressed in https://github.com/nishad/udemy-dl/pull/134. You can check the project wiki for further assistance on installing a development version from this repository.

**Closed by nishad** 2016-08-28 19:03 UTC
