### ISSUE TITLE
[BUG] Failed to get course ID

### ISSUE THREAD

**Issue by plotti** [nishad/udemy-dl#52] opened 2016-03-10 09:22 UTC
**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read and understood the [contributors guide]().
- [x] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I have never used the project.
- [ ] I have used the project briefly.
- [x] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

```
udemy-dl https://www.udemy.com/data-science-deep-learning-in-theano-tensorflow  -u xxxx@xxxx -p xxxx
Downloading to: /Users/xxx/ONLINE COURSES/data-science-deep-learning-in-theano-tensorflow

Failed to get course ID
```

```
udemy-dl -v
udemy-dl 0.2.0
```

ON Mac installed with pip. No update available so far.

**Comment by nishad** [comment] 2016-03-10 16:48
This error is already reported by some users, https://github.com/nishad/udemy-dl/issues/48. Unfortunately I couldn't reproduce this error. You can try with the current development version, since there is no stable releases yet for PyPI. 
Instructions are here https://github.com/nishad/udemy-dl/wiki/Installing-development-version. But I'm not so sure if that will resolve this issue.

**Comment by plotti** [comment] 2016-03-10 16:50
Installed the dev version and now getting:

Trying to log in ... and we're done.
Failed to get course ID

**Comment by plotti** [comment] 2016-03-10 16:57
I've created a save from the site maybe it helps you.

[Data Science: Practical Deep Learning in Theano + TensorFlow | Udemy.zip](https://github.com/nishad/udemy-dl/files/167612/Data.Science.Practical.Deep.Learning.in.Theano.TensorFlow.Udemy.zip)

**Comment by plotti** [comment] 2016-03-10 18:38
hmm debug doesnt output anything. The version i was able to download was:
udemy-dl 0.2.1-alpha
if I try to compile from git i am getting:
➜  udemy-dl git:(master) ✗ python setup.py
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

**Comment by mukhlesur-millon** [comment] 2016-03-10 18:40
usage: `python setup.py install`

**Comment by nishad** [comment] 2016-03-10 18:41
You can install it via pip
```
pip install --upgrade https://github.com/nishad/udemy-dl/zipball/master
```
and try this first
```
udemy-dl -v
```
That should output `udemy-dl 0.2.1-alpha`

**Comment by mukhlesur-millon** [comment] 2016-03-10 19:18
course id can be grabbed from image link :smiley:

**Comment by nishad** [comment] 2016-03-10 21:19
@plotti, it is fixed with https://github.com/nishad/udemy-dl/commit/ee6ecab864fc0adb5eb46d92f6a67ad370e58d27, you can try again with the latest development version. @mukhlesur-millon, you can still create a PR, since https://github.com/nishad/udemy-dl/blob/master/src/udemy_dl/udemy_dl.py#L106 is a quick and dirty approach.  

I will be removing comment with debug files link to ensure privacy.

:sake: Kanpai !!!

**Comment by plotti** [comment] 2016-03-10 21:22
Excellent work! Let me have a try .

**Closed** 2016-03-10 23:54 UTC
Labels: duplicate, Unknown
