### ISSUE TITLE
[QUESTION] ERROR-1198 in downloading course

### ISSUE THREAD

**Issue by iamsmith41** [nishad/udemy-dl#213] opened 2017-04-24 04:48 UTC
Version : **udemy-dl-windows-2.1.2**

**In raising this issue, I confirm the following (please check boxes, eg [X]):**

- [x ] I have read and understood the [contributors guide](https://github.com/nishad/udemy-dl/blob/master/.github/CONTRIBUTING.md).
- [x ] I have checked that the bug-fix I am reporting can be replicated, or that the feature I am suggesting isn't already present.
- [x ] I have checked that the issue I'm posting isn't already reported.
- [x ] I have checked that the issue I'm porting isn't already solved and no duplicates exist in [closed issues](https://github.com/nishad/udemy-dl/issues?q=is%3Aissue+is%3Aclosed) and in [opened issues](https://github.com/nishad/udemy-dl/issues)
- [x ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one, eg [X]):**

- [x ] I have never used the project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.
- [ ] I am an active contributor to the project.

**If the project maintainer has any additional requirements, they will be listed here.**

- No additional requirements.

---

Hi,

Kindly assist in this.
I have a udemy business account.

I changed the url to this-
https://company.udemy.com/course_name ---------> https://www.udemy.com/course_name

I used the changed one for one course -
**udemy-dl.exe https://www.udemy.com/course_name1 -u user -p pass**

and it successfully downloaded the whole course.

When I am trying for another courses, for most of them I am getting -

```
[INFO-127] Trying to log in ...
[INFO-157] Login success.
[INFO-189] Found course id: 12345678
[ERROR-1198] Traceback (most recent call last):
  File "<string>", line 889, in <module>
  File "<string>", line 886, in main
  File "<string>", line 705, in udemy_dl
  File "<string>", line 382, in get_data_links
**KeyError: u'results'**
None
udemy_dl returned -1
```

For some others I am getting -

```
[INFO-127] Trying to log in ...
[INFO-157] Login success.
[INFO-189] Found course id: 545698
Getting course data: 1.15% [--------------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 1.72% [--------------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 2.87% [=-------------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 3.45% [=-------------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 4.02% [=-------------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 4.60% [=-------------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 5.17% [=-------------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 5.75% [=-------------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 6.32% [=-------------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 6.90% [=-------------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 7.47% [=-------------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 8.05% [==------------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 8.62% [==------------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 9.20% [==------------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 9.77% [==------------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 10.34% [==------------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 10.92% [==------------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 12.64% [===-----------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 13.22% [===-----------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 13.79% [===-----------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 14.37% [===-----------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 14.94% [===-----------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 16.67% [===-----------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 17.24% [===-----------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 17.82% [====----------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 18.39% [====----------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 18.97% [====----------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 19.54% [====----------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 20.11% [====----------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 20.69% [====----------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 21.26% [====----------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 22.99% [=====---------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 23.56% [=====---------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 24.14% [=====---------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 24.71% [=====---------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 25.29% [=====---------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 27.01% [=====---------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 27.59% [======--------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 28.16% [======--------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 28.74% [======--------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 29.31% [======--------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 29.89% [======--------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 31.61% [======--------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 32.18% [======--------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 32.76% [=======-------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 33.33% [=======-------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 33.91% [=======-------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 35.63% [=======-------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 36.21% [=======-------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 36.78% [=======-------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 37.36% [=======-------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 37.93% [========------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 38.51% [========------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 39.08% [========------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 39.66% [========------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 40.23% [========------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 40.80% [========------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 41.38% [========------------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 43.10% [=========-----------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 43.68% [=========-----------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 44.25% [=========-----------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 44.83% [=========-----------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 45.40% [=========-----------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 45.98% [=========-----------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 46.55% [=========-----------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 47.13% [=========-----------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 47.70% [==========----------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 48.28% [==========----------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 50.00% [==========----------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 50.57% [==========----------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 51.15% [==========----------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 51.72% [==========----------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 52.30% [==========----------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 52.87% [===========---------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 53.45% [===========---------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 54.02% [===========---------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 54.60% [===========---------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 55.17% [===========---------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 55.75% [===========---------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 56.32% [===========---------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 56.90% [===========---------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 57.47% [===========---------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 58.05% [============--------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 58.62% [============--------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 59.20% [============--------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 59.77% [============--------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 60.34% [============--------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 62.07% [============--------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 62.64% [=============-------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 63.22% [=============-------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 63.79% [=============-------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 64.37% [=============-------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 64.94% [=============-------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 65.52% [=============-------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 66.09% [=============-------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 66.67% [=============-------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 67.24% [=============-------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 67.82% [==============------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 68.39% [==============------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 68.97% [==============------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 69.54% [==============------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 71.26% [==============------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 71.84% [==============------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 72.41% [==============------] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 72.99% [===============-----] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 73.56% [===============-----] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 74.14% [===============-----] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 74.71% [===============-----] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 75.29% [===============-----] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 75.86% [===============-----] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 76.44% [===============-----] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 77.01% [===============-----] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 77.59% [================----] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 78.16% [================----] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 78.74% [================----] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 80.46% [================----] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 81.03% [================----] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 81.61% [================----] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 82.18% [================----] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 82.76% [=================---] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 83.33% [=================---] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 83.91% [=================---] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 85.63% [=================---] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 86.21% [=================---] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 86.78% [=================---] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 87.36% [=================---] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 87.93% [==================--] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 89.66% [==================--] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 90.23% [==================--] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 90.80% [==================--] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 91.38% [==================--] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 91.95% [==================--] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 92.53% [===================-] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 93.10% [===================-] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 93.68% [===================-] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 94.25% [===================-] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 94.83% [===================-] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 95.40% [===================-] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 95.98% [===================-] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 96.55% [===================-] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 97.13% [===================-] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 97.70% [====================] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 98.28% [====================] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 98.85% [====================] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 99.43% [====================] [CRITICAL-261] Skipped. Expected quality not found!
Getting course data: 100.00% [====================] Done
```

Kindly suggest for both errors.

**Comment by iamsmith41** [comment] 2017-04-24 18:04
Hi,
Can anyone suggest about the errors?

**Comment by Babazon** [comment] 2017-04-25 04:40
Another person has released a forked version of this package that solved the "Expected quality not found" problem. I was able to download a few of my courses thanks to that. 

Simply install his fork:

`pip install -U git+https://github.com/smeggingsmegger/udemy-dl.git@master
`
And the app will work with the same commands.

**Comment by iamsmith41** [comment] 2017-04-25 17:01
Below is the error, I went to the directory where udemy-dl.exe is and ran the command:

```
Collecting git+https://github.com/smeggingsmegger/udemy-dl.git@master
  Cloning https://github.com/smeggingsmegger/udemy-dl.git (to master) to c:\users\-#-$-a~1\appdata\local\temp\pip-2hsfuz-build
  Error [Error 2] The system cannot find the file specified while executing command git clone -q https://github.com/smeggingsmegger/udemy-dl.git c:\users\-#-$-a~1\appdata\local\temp\pip-2hsfuz-build
Cannot find command 'git'
You are using pip version 7.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

**Comment by iamsmith41** [comment] 2017-04-25 19:40
Hi ok I added git in the environment path. It downloaded few things as per the above command.

Below is the output of the command with an error in last:

```
Collecting git+https://github.com/smeggingsmegger/udemy-dl.git@master
  Cloning https://github.com/smeggingsmegger/udemy-dl.git (to master) to c:\users\-#-$-a~1\appdata\local\temp\pip-mbx9zg-build
Requirement already up-to-date: requests in c:\python27\lib\site-packages (from udemy-dl==0.2.3a0)
Requirement already up-to-date: unicode-slugify in c:\python27\lib\site-packages (from udemy-dl==0.2.3a0)
Requirement already up-to-date: colorlog in c:\python27\lib\site-packages (from udemy-dl==0.2.3a0)
Requirement already up-to-date: future in c:\python27\lib\site-packages (from udemy-dl==0.2.3a0)
Collecting python-pptx (from udemy-dl==0.2.3a0)
  Using cached python-pptx-0.6.5.tar.gz
Requirement already up-to-date: six in c:\python27\lib\site-packages (from unicode-slugify->udemy-dl==0.2.3a0)
Requirement already up-to-date: unidecode in c:\python27\lib\site-packages (from unicode-slugify->udemy-dl==0.2.3a0)
Requirement already up-to-date: colorama in c:\python27\lib\site-packages (from colorlog->udemy-dl==0.2.3a0)
Requirement already up-to-date: lxml>=3.1.0 in c:\python27\lib\site-packages (from python-pptx->udemy-dl==0.2.3a0)
Collecting Pillow>=2.6.1 (from python-pptx->udemy-dl==0.2.3a0)
  Using cached Pillow-4.1.0.tar.gz
Collecting XlsxWriter>=0.5.7 (from python-pptx->udemy-dl==0.2.3a0)
  Using cached XlsxWriter-0.9.6-py2.py3-none-any.whl
Requirement already up-to-date: olefile in c:\python27\lib\site-packages (from Pillow>=2.6.1->python-pptx->udemy-dl==0.2.3a0)
Installing collected packages: Pillow, XlsxWriter, python-pptx, udemy-dl
  Running setup.py install for Pillow
    Complete output from command c:\python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\-#-$-a~1\\appdata\\local\\temp\\pip-build-cicosv\\Pillow\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\-#-$-a~1\appdata\local\temp\pip-ry2lvo-record\install-record.txt --single-version-externally-managed --compile:
    Single threaded build for windows
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-2.7
    creating build\lib.win-amd64-2.7\PIL
    copying PIL\BdfFontFile.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\BmpImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\BufrStubImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\ContainerIO.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\CurImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\DcxImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\DdsImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\EpsImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\ExifTags.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\features.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\FitsStubImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\FliImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\FontFile.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\FpxImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\FtexImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\GbrImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\GdImageFile.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\GifImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\GimpGradientFile.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\GimpPaletteFile.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\GribStubImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\Hdf5StubImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\IcnsImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\IcoImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\Image.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\ImageChops.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\ImageCms.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\ImageColor.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\ImageDraw.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\ImageDraw2.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\ImageEnhance.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\ImageFile.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\ImageFilter.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\ImageFont.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\ImageGrab.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\ImageMath.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\ImageMode.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\ImageMorph.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\ImageOps.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\ImagePalette.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\ImagePath.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\ImageQt.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\ImageSequence.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\ImageShow.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\ImageStat.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\ImageTk.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\ImageTransform.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\ImageWin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\ImImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\ImtImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\IptcImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\Jpeg2KImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\JpegImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\JpegPresets.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\McIdasImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\MicImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\MpegImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\MpoImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\MspImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\OleFileIO.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\PaletteFile.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\PalmImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\PcdImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\PcfFontFile.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\PcxImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\PdfImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\PixarImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\PngImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\PpmImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\PsdImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\PSDraw.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\PyAccess.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\SgiImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\SpiderImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\SunImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\TarIO.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\TgaImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\TiffImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\TiffTags.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\WalImageFile.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\WebPImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\WmfImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\XbmImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\XpmImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\XVThumbImagePlugin.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\_binary.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\_tkinter_finder.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\_util.py -> build\lib.win-amd64-2.7\PIL
    copying PIL\__init__.py -> build\lib.win-amd64-2.7\PIL
    running egg_info
    writing requirements to Pillow.egg-info\requires.txt
    writing Pillow.egg-info\PKG-INFO
    writing top-level names to Pillow.egg-info\top_level.txt
    writing dependency_links to Pillow.egg-info\dependency_links.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'Pillow.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs\_static'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching '.travis'
    warning: no previously-included files found matching '.travis\*'
    warning: no previously-included files found matching 'appveyor.yml'
    warning: no previously-included files found matching 'build_children.sh'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    writing manifest file 'Pillow.egg-info\SOURCES.txt'
    running build_ext


    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\-#-$-a~1\appdata\local\temp\pip-build-cicosv\Pillow\setup.py", line 756, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:

    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html



    ----------------------------------------
_**Command "c:\python27\python.exe -c "import setuptools, tokenize;__file__='c:\\users\\-#-$-a~1\\appdata\\local\\temp\\pip-build-cicosv\\Pillow\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\-#-$-a~1\appdata\local\temp\pip-ry2lvo-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in c:\users\-#-$-a~1\appdata\local\temp\pip-build-cicosv\Pillow**_
You are using pip version 7.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

```
```
> python -m pip install --upgrade pip
Requirement already up-to-date: pip in d:\python\python36\lib\site-packages
```

And still getting the same error of Expected quality not found!

**Comment by nishad** [comment] 2017-05-06 03:31
Duplicate of https://github.com/nishad/udemy-dl/issues/207

**Closed by nishad** 2017-05-06 03:31 UTC
Labels: duplicate

**Comment by iamsmith41** [comment] 2017-05-09 17:46
Hi Nishad,

In #207 there is no solution for windows version of udemy-dl.exe, I am still getting the same error.

**Comment by iamsmith41** [comment] 2017-05-09 17:48
Also, I posted initially one more error in #213

```
[INFO-127] Trying to log in ...
[INFO-157] Login success.
[INFO-189] Found course id: 12345678
[ERROR-1198] Traceback (most recent call last):
  File "<string>", line 889, in <module>
  File "<string>", line 886, in main
  File "<string>", line 705, in udemy_dl
  File "<string>", line 382, in get_data_links
**KeyError: u'results'**
None
udemy_dl returned -1
```

What is the error saying and what can be the resolution? Thanks in advance.
